name: shy
version: 0.1.0.0
synopsis: safely try out shell one-liners with live feedback
description: Please see the README at <https://github.com/jwoudenberg/shy>.
author: Jasper Woudenberg
maintainer: mail@jasperwoudenberg.com
copyright: 2021 Jasper Woudenberg
homepage: https://github.com/jwoudenberg/shy#readme
license-file: LICENSE
github: jwoudenberg/shy
extra-doc-files:
- README.md
library:
  exposed-modules:
  - Shy
  source-dirs: src
executables:
  shy:
    dependencies:
    - shy
    main: Main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts "-with-rtsopts=-N -T"
    - -O2
dependencies:
- base >= 4.10.1.0 && < 5
- brick >= 0.62 && < 0.66
- text >= 1.2.4.0 && < 1.3
ghc-options:
- -Wall
- -Werror
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wpartial-fields
- -Wredundant-constraints
- -Wincomplete-uni-patterns
default-extensions:
- DeriveGeneric
- GeneralizedNewtypeDeriving
- NamedFieldPuns
- NumericUnderscores
- OverloadedStrings
- ScopedTypeVariables
- StrictData
